AllCops:
  TargetRubyVersion: 2.6
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
    - '**/config.ru'
    - '**/*.rake'
  Exclude:
    - vendor/**/*
    - db/migrations/**/*

  DisplayCopNames:
    Enabled: true

  DisplayStyleGuide:
    Enabled: true

Style/FileName:
  Exclude:
  - Guardfile

Metrics/BlockLength:
  Exclude:
    - spec/**/*
