version: '2'
services:
  web:
    build: .
    image: sgh-eltern/pdf-service
    restart: unless-stopped
    links:
      - electron-renderer
    ports:
      - 9292:9292
    environment:
      - RENDERER_ACCESS_KEY
  electron-renderer:
    image: msokk/electron-render-service
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - RENDERER_ACCESS_KEY
      - HOSTNAME=0.0.0.0
