version: '2'
services:
  web:
    build: .
    image: sgh-eltern/pdf-service
    restart: unless-stopped
    links:
      - electron-renderer
    ports:
      - ${WEB_PORT}:9292
    environment:
      - RENDERER_ACCESS_KEY
  electron-renderer:
    image: msokk/electron-render-service
    restart: unless-stopped
    environment:
      - RENDERER_ACCESS_KEY
